import Head from "next/head";
import styles from "@/styles/Home.module.css";
import HighlightGameCard from "@/components/HightlightGameCard";
import TopSoccerGamesSection from "@/components/TopSoccerGamesSection";
import { HIGHLIGHT_GAMES } from "@/constants";
import Header from "@/components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kazix | Betting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <section className={`container ${styles.highlightGameContainer}`}>
        {HIGHLIGHT_GAMES.map(({ gameId, ...rest }) => (
          <HighlightGameCard key={gameId} id={gameId} {...rest} />
        ))}
      </section>
      <TopSoccerGamesSection />
    </>
  );
}
