export const TOP_GAMES = [
  {
    gameId: "12",
    tournament: "Argentina - Liga Professional",
    team1: "Barracas Central",
    team2: "CA Central Cordoba SE",
    time: "Today, 21:30",
    team1WinPt: 2.3,
    team2WinPt: 5,
    drawPt: 1.3,
  },
  {
    gameId: "13",
    tournament: "Argentina - Liga Professional",
    team1: "Barracas Central",
    team2: "CA Central Cordoba SE",
    time: "Today, 21:30",
    team1WinPt: 2.3,
    team2WinPt: 5,
    drawPt: 1.3,
  },
  {
    gameId: "14",
    tournament: "Argentina - Liga Professional",
    team1: "Barracas Central",
    team2: "CA Central Cordoba SE",
    time: "Today, 21:30",
    team1WinPt: 2.3,
    team2WinPt: 5,
    drawPt: 1.3,
  },
  {
    gameId: "15",
    tournament: "Argentina - Liga Professional",
    team1: "Barracas Central",
    team2: "CA Central Cordoba SE",
    time: "Today, 21:30",
    team1WinPt: 2.3,
    team2WinPt: 5,
    drawPt: 1.3,
  },
  {
    gameId: "16",
    tournament: "Argentina - Liga Professional",
    team1: "Barracas Central",
    team2: "CA Central Cordoba SE",
    time: "Today, 21:30",
    team1WinPt: 2.3,
    team2WinPt: 5,
    drawPt: 1.3,
  },
  {
    gameId: "17",
    tournament: "Argentina - Liga Professional",
    team1: "Barracas Central",
    team2: "CA Central Cordoba SE",
    time: "Today, 21:30",
    team1WinPt: 2.3,
    team2WinPt: 5,
    drawPt: 1.3,
  },
  {
    gameId: "18",
    tournament: "Argentina - Liga Professional",
    team1: "Barracas Central",
    team2: "CA Central Cordoba SE",
    time: "Today, 21:30",
    team1WinPt: 2.3,
    team2WinPt: 5,
    drawPt: 1.3,
  },
  {
    gameId: "19",
    tournament: "Argentina - Liga Professional",
    team1: "Barracas Central",
    team2: "CA Central Cordoba SE",
    time: "Today, 21:30",
    team1WinPt: 2.3,
    team2WinPt: 5,
    drawPt: 1.3,
  },
  {
    gameId: "20",
    tournament: "Argentina - Liga Professional",
    team1: "Barracas Central",
    team2: "CA Central Cordoba SE",
    time: "Today, 21:30",
    team1WinPt: 2.3,
    team2WinPt: 5,
    drawPt: 1.3,
  },
];


export const HIGHLIGHT_GAMES = [
  {
    gameId: "1",
    competetion: ["England", "Premier League"],
    team1: "Tottenham",
    team2: "Leicester City",
    team1WinPt: 1.05,
    team2WinPt: 5.13,
    team1Goals: 4,
    team2Goals: 2,
    drawPt: 2.4,
  },
  {
    gameId: "2",
    competetion: ["England", "Premier League"],
    team1: "Tottenham",
    team2: "Leicester City",
    team1Goals: 4,
    team2Goals: 2,
    team1WinPt: 1.05,
    team2WinPt: 5.13,
    drawPt: 2.4,
  },
];
